### ISSUE TITLE
Mobile NAS nano will fail in call contract.

### ISSUE THREAD

**Issue by 5sWind** [nebulasio/nebPay.js#43]
The error is cause for writing review on http://nebulas.cool/.
One example is: https://explorer.nebulas.io/#/tx/28bd020a001b89f93386d18da5f04315767b67d46d7d523f79f07d872f7594a8
When call contract using NAS nano, the transaction status will be fail in 3 seconds. While switch to web extension wallet to call contract, the transaction status will be success.

The tx issue maybe in Gas Limit, Args, and Value to send.

**Comment by yupnano** [comment]
很抱歉没有及时回复，刚查了一下，这个交易失败原因是gas不够，应该是gas limit太小了，钱包稍后会增加更改gas limit的功能。

PS：目前浏览器上还没增加显示失败原因的功能（预计很快会更新该功能），目前可以直接用 api [`getTransactionReceipt`](https://github.com/nebulasio/wiki/blob/master/rpc.md#gettransactionreceipt) 去查询原因，请参考博客[使用 Postman 访问 Nebulas API](https://blog.csdn.net/ycyzyp/article/details/80552440)

```
{
    "result": {
        "hash": "28bd020a001b89f93386d18da5f04315767b67d46d7d523f79f07d872f7594a8",
        "chainId": 1,
        "from": "n1HHRFAkEoUHnKusQojHZbpmdJj8pJSF4Wf",
        "to": "n1oXPK4pGpqDLYoZKvpVUot2gbzveF7Aizz",
        "value": "0",
        "nonce": "5",
        "timestamp": "1528039533",
        "type": "call",
        "data": "eyJGdW5jdGlvbiI6ImNvbW1lbnRTdWJtaXQiLCJBcmdzIjoiW1wiaWQzMDU1NTE4MzkwXCIsXCJ7XFxcInNjb3JlXFxcIjo1LFxcXCJhdXRob3JcXFwiOlxcXCI1c1dpbmRcXFwiLFxcXCJjb250ZW50XFxcIjpcXFwi6L+Z5Liq5L2c6ICF5b6I5a6z576e77yM5LuA5LmI6YO95rKh5pyJ5YaZ44CCXFxcIn1cIl0ifQ==",
        "gas_price": "1000000",
        "gas_limit": "50000",
        "contract_address": "",
        "status": 0,
        "gas_used": "50000",
        "execute_error": "insufficient gas",
        "execute_result": "null"
    }
}
```
